### ISSUE TITLE
Social security status

### ISSUE THREAD

**Issue by martab0** [AFAFAF1357/TEST#13]
average salary, minimum salary - przydadzą się odsyłacze do strony, gdzie można sprawdzić aktualne wielkości

Think if you want to benefit from one of the above entitlements - brzmi tak, jakby można sobie było wybrać, czy się płaci poszczególne składki?

**Comment by AFAFAF1357** [comment]
Doprecyzowałam. Można wybrać, czy chce się skorzystać z którejś z ulg.
